# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-25 09:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elasticsearchapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MerchantServices',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('native_id', models.BigIntegerField(default=None)),
                ('parent_id', models.BigIntegerField(default=None)),
                ('top_id', models.BigIntegerField(default=None)),
                ('edizm_id', models.BigIntegerField(default=None)),
                ('status', models.IntegerField(default=None)),
                ('typ', models.CharField(default='', max_length=225)),
                ('spname', models.CharField(default='', max_length=225)),
                ('name', models.TextField()),
                ('allnames', models.TextField()),
                ('folder', models.TextField(default=None)),
                ('srch', models.TextField(blank=True, default='')),
                ('popularity', models.BigIntegerField()),
                ('z_id', models.TextField()),
                ('terms', models.TextField(default='')),
                ('stem_terms', models.TextField(default='')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='blogpost',
            name='author',
        ),
        migrations.DeleteModel(
            name='BlogPost',
        ),
    ]
